/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.projeto.poo.view;

import control.ControlGeral;
import java.awt.CardLayout;
import javax.swing.table.DefaultTableModel;
import DAO.Sistema;
import java.util.HashMap;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.TableColumn;
import model.*;

/**
 *
 * @author Erian
 */
public class TelaInicio extends javax.swing.JFrame {
    
    private ControlGeral controlador;
    private Sistema s;
    private Aluno alunoLogado;
    private int numeroSemestreAtual = 0;
    private CardLayout c1;
    /**
     * Creates new form TelaInicio
     */
    public TelaInicio() {
        initComponents();
        
        
        
        this.textLogin.setText("");
        this.controlador = new ControlGeral("UFV");
        this.s = new Sistema();
        this.s.CadastrarProfessores(this.controlador);

        // Injetando dados no sistema
        this.s.CadastrarDisciplinas(this.controlador);
        this.s.CadastrarCurso(this.controlador);
        this.s.CadastrarDepartamento(this.controlador);
        this.s.CadastrarGrade(this.controlador);
        this.s.CadastrarSemestre(this.controlador);
        this.s.CadastrarDisciplinaSemestre(this.controlador);
        this.s.Conectar(this.controlador); 
        this.s.VincularDisciplinasDaInstituicao(this.controlador);
        
        this.menuItemAbaPesquisa.setVisible(false);
        this.menuItemGrade.setVisible(false);
        this.menuItemPerfil.setVisible(false);
        
        c1 = (CardLayout) this.jPanel1.getLayout();
        
        
 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        textLogin = new javax.swing.JTextField();
        botaoLogin = new javax.swing.JButton();
        labelTitulo = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        comboBox_I = new javax.swing.JComboBox<>();
        labelTituloTabela = new javax.swing.JLabel();
        botaoTabela = new javax.swing.JButton();
        textPesquisa = new javax.swing.JTextField();
        panelPerfilAluno = new javax.swing.JPanel();
        labelNome = new javax.swing.JLabel();
        labelEmail = new javax.swing.JLabel();
        labelMatricula = new javax.swing.JLabel();
        labelNome1 = new javax.swing.JLabel();
        labelEmail1 = new javax.swing.JLabel();
        labelMatricula1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelaSemestreAtual = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        botaoHistorico = new javax.swing.JButton();
        comboBoxHistorico = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        labelCreditosNum = new javax.swing.JLabel();
        labelCreditosPorcentagem = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        panelGrade = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textCodigoDisciplina = new javax.swing.JTextField();
        comboBoxNumSemestre = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableGrade = new javax.swing.JTable();
        botaoPesquisarDiscp = new javax.swing.JButton();
        botaoConfirmar = new javax.swing.JButton();
        textFieldSemestreAtual = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        botaoDefinirSemestre = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        labelResultadoOperacao = new javax.swing.JLabel();
        panelCadastro = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        comboBoxCadastro = new javax.swing.JComboBox<>();
        textFieldNome = new javax.swing.JTextField();
        textFieldEmail = new javax.swing.JTextField();
        textFieldMatricula = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        botaoCadastro = new javax.swing.JButton();
        labelCadastro = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuItemGrade = new javax.swing.JMenuItem();
        menuItemAbaPesquisa = new javax.swing.JMenuItem();
        menuItemPerfil = new javax.swing.JMenuItem();
        menuItemSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.CardLayout());

        textLogin.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        textLogin.setText("jTextField1");
        textLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textLoginActionPerformed(evt);
            }
        });

        botaoLogin.setText("Entrar");
        botaoLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLoginActionPerformed(evt);
            }
        });

        labelTitulo.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo.setText("Acompanhamento Acadêmico");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(332, 332, 332)
                        .addComponent(textLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(377, 377, 377)
                        .addComponent(botaoLogin)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(textLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(botaoLogin)
                .addContainerGap(220, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, "card2");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        comboBox_I.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboBox_I.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBox_IActionPerformed(evt);
            }
        });

        labelTituloTabela.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        labelTituloTabela.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTituloTabela.setText("Titulo");

        botaoTabela.setText("Pesquisar");
        botaoTabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoTabelaActionPerformed(evt);
            }
        });

        textPesquisa.setText("campoPesquisa");
        textPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPesquisaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textPesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                    .addComponent(comboBox_I, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botaoTabela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelTituloTabela, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(147, 147, 147))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(labelTituloTabela, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(comboBox_I, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(textPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(botaoTabela)))
                .addContainerGap(159, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, "cardPesquisa");

        labelNome.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        labelNome.setText("Nome:");

        labelEmail.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        labelEmail.setText("Matrícula:");

        labelMatricula.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        labelMatricula.setText("jLabel3");

        labelNome1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        labelNome1.setText("Nome:");

        labelEmail1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        labelEmail1.setText("E-mail:");

        labelMatricula1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        labelMatricula1.setText("Matrícula:");

        tabelaSemestreAtual.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tabelaSemestreAtual);
        if (tabelaSemestreAtual.getColumnModel().getColumnCount() > 0) {
            tabelaSemestreAtual.getColumnModel().getColumn(0).setResizable(false);
            tabelaSemestreAtual.getColumnModel().getColumn(1).setResizable(false);
            tabelaSemestreAtual.getColumnModel().getColumn(2).setResizable(false);
            tabelaSemestreAtual.getColumnModel().getColumn(3).setResizable(false);
        }

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Semestre atual");

        botaoHistorico.setText("Pesquisar");
        botaoHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoHistoricoActionPerformed(evt);
            }
        });

        comboBoxHistorico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Historico" }));
        comboBoxHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxHistoricoActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Créditos cursados:");

        labelCreditosNum.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        labelCreditosNum.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelCreditosNum.setText("labelCre");

        labelCreditosPorcentagem.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        labelCreditosPorcentagem.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelCreditosPorcentagem.setText("labelPorcen");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setText("Porcentagem de créditos:");

        javax.swing.GroupLayout panelPerfilAlunoLayout = new javax.swing.GroupLayout(panelPerfilAluno);
        panelPerfilAluno.setLayout(panelPerfilAlunoLayout);
        panelPerfilAlunoLayout.setHorizontalGroup(
            panelPerfilAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPerfilAlunoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPerfilAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPerfilAlunoLayout.createSequentialGroup()
                        .addGroup(panelPerfilAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(labelMatricula1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelNome1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelEmail1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(panelPerfilAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                        .addGroup(panelPerfilAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPerfilAlunoLayout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPerfilAlunoLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(179, 179, 179))))
                    .addGroup(panelPerfilAlunoLayout.createSequentialGroup()
                        .addGroup(panelPerfilAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelPerfilAlunoLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelCreditosPorcentagem, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelPerfilAlunoLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelCreditosNum, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelPerfilAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botaoHistorico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboBoxHistorico, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(230, 230, 230))))
        );
        panelPerfilAlunoLayout.setVerticalGroup(
            panelPerfilAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPerfilAlunoLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panelPerfilAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelPerfilAlunoLayout.createSequentialGroup()
                        .addGroup(panelPerfilAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelNome1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(panelPerfilAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(panelPerfilAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelMatricula1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelPerfilAlunoLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(comboBoxHistorico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPerfilAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoHistorico)
                    .addGroup(panelPerfilAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelCreditosNum, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(panelPerfilAlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCreditosPorcentagem, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55))
        );

        jPanel1.add(panelPerfilAluno, "cardPerfil");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 2, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Grade Curricular");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        textCodigoDisciplina.setText("codigoDisc");

        comboBoxNumSemestre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semestre" }));

        tableGrade.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tableGrade);
        if (tableGrade.getColumnModel().getColumnCount() > 0) {
            tableGrade.getColumnModel().getColumn(0).setResizable(false);
            tableGrade.getColumnModel().getColumn(1).setResizable(false);
            tableGrade.getColumnModel().getColumn(2).setResizable(false);
            tableGrade.getColumnModel().getColumn(3).setResizable(false);
        }

        botaoPesquisarDiscp.setText("Pesquisar");
        botaoPesquisarDiscp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPesquisarDiscpActionPerformed(evt);
            }
        });

        botaoConfirmar.setText("Confirmar");
        botaoConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoConfirmarActionPerformed(evt);
            }
        });

        textFieldSemestreAtual.setText("numSemestre atual");
        textFieldSemestreAtual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldSemestreAtualActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Digite número semestre atual:");

        botaoDefinirSemestre.setText("Definir");
        botaoDefinirSemestre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDefinirSemestreActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Pesquisar Disciplina");

        labelResultadoOperacao.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        labelResultadoOperacao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelResultadoOperacao.setText("label-status-operacao");

        javax.swing.GroupLayout panelGradeLayout = new javax.swing.GroupLayout(panelGrade);
        panelGrade.setLayout(panelGradeLayout);
        panelGradeLayout.setHorizontalGroup(
            panelGradeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGradeLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGradeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textFieldSemestreAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoDefinirSemestre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGradeLayout.createSequentialGroup()
                .addGroup(panelGradeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelGradeLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(botaoPesquisarDiscp, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelGradeLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(panelGradeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addGroup(panelGradeLayout.createSequentialGroup()
                                .addComponent(textCodigoDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(comboBoxNumSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(195, 195, 195))
            .addGroup(panelGradeLayout.createSequentialGroup()
                .addGap(269, 269, 269)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelGradeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelResultadoOperacao, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(136, 136, 136))
        );
        panelGradeLayout.setVerticalGroup(
            panelGradeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGradeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(panelGradeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelGradeLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(comboBoxNumSemestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(textCodigoDisciplina, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelGradeLayout.createSequentialGroup()
                        .addGroup(panelGradeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(textFieldSemestreAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(botaoDefinirSemestre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(71, 71, 71)))
                .addGroup(panelGradeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoPesquisarDiscp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelGradeLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(botaoConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addComponent(labelResultadoOperacao)
                .addGap(58, 58, 58))
        );

        jPanel1.add(panelGrade, "cardGrade");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Cadastro");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        comboBoxCadastro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1" }));

        textFieldNome.setText("jTextField1");

        textFieldEmail.setText("jTextField2");

        textFieldMatricula.setText("jTextField3");
        textFieldMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldMatriculaActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Tipo de cadastro:");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Nome:");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("E-mail:");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("Matrícula:");

        botaoCadastro.setText("Confimar");
        botaoCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastroActionPerformed(evt);
            }
        });

        labelCadastro.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        labelCadastro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCadastro.setText("jLabel10");

        javax.swing.GroupLayout panelCadastroLayout = new javax.swing.GroupLayout(panelCadastro);
        panelCadastro.setLayout(panelCadastroLayout);
        panelCadastroLayout.setHorizontalGroup(
            panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCadastroLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCadastroLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(comboBoxCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(panelCadastroLayout.createSequentialGroup()
                        .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(58, 58, 58)
                        .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelCadastroLayout.createSequentialGroup()
                                .addComponent(botaoCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(panelCadastroLayout.createSequentialGroup()
                                .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(textFieldEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                                    .addComponent(textFieldNome)
                                    .addComponent(textFieldMatricula))
                                .addGap(626, 626, 626))))))
            .addGroup(panelCadastroLayout.createSequentialGroup()
                .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCadastroLayout.createSequentialGroup()
                        .addGap(284, 284, 284)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCadastroLayout.createSequentialGroup()
                        .addGap(299, 299, 299)
                        .addComponent(labelCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCadastroLayout.setVerticalGroup(
            panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCadastroLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelCadastroLayout.createSequentialGroup()
                        .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboBoxCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(46, 46, 46)
                        .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(55, 55, 55))
                    .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(textFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoCadastro)
                    .addComponent(labelCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
        );

        jPanel1.add(panelCadastro, "cardCadastro");

        jMenu1.setText("Menu");

        menuItemGrade.setText("Grade");
        menuItemGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemGradeActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemGrade);

        menuItemAbaPesquisa.setText("Pesquisar");
        menuItemAbaPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemAbaPesquisaActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemAbaPesquisa);

        menuItemPerfil.setText("Perfil");
        menuItemPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemPerfilActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemPerfil);

        menuItemSair.setText("Sair");
        menuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSairActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemSair);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void RemoverLinhasTabela(DefaultTableModel model){
        int rowCount = model.getRowCount();
        //Remove rows one by one from the end of the table
        for (int i = rowCount - 1; i >= 0; i--) {
            model.removeRow(i);
        }
    }
    private void comboBox_IActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBox_IActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBox_IActionPerformed

    private void botaoTabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoTabelaActionPerformed
        // TODO add your handling code here:
        if (this.jTable1.getColumnCount() != 4){
            TableColumn aColumn = new TableColumn();
            this.jTable1.addColumn(aColumn);
        }
        DefaultTableModel model = (DefaultTableModel) this.jTable1.getModel();
        RemoverLinhasTabela(model);
        // Tentar pegar um listener para verificar mudanca
        if (this.comboBox_I.getSelectedItem().toString().equals("Disciplinas - Instituição") ){
            
            this.labelTituloTabela.setText("Disciplinas - Instituição");
            
            this.jTable1.getColumnModel().getColumn(1).setPreferredWidth(200);
            this.jTable1.getColumnModel().getColumn(0).setHeaderValue("Código");
            this.jTable1.getColumnModel().getColumn(1).setHeaderValue("Nome");
            this.jTable1.getColumnModel().getColumn(2).setHeaderValue("Professor");
            this.jTable1.getColumnModel().getColumn(3).setHeaderValue("Créditos");
            this.jTable1.getTableHeader().repaint();            
            
            
            
            HashMap<String, Disciplina> discp = this.controlador.getInstituicao().getDisciplinas(); 
            for (String codigo : discp.keySet()){
                Object[] row = {discp.get(codigo).getCodigo(), discp.get(codigo).getNome(), discp.get(codigo).getProfessor(), discp.get(codigo).getQntCreditos()};
                model.addRow(row);
            }
            
        }
        else if (this.comboBox_I.getSelectedItem().toString().equals("Disciplinas - Semestre") ){
            
            int numSemestre = Integer.parseInt(this.textPesquisa.getText());
            Semestre semestre = this.controlador.RetornarSemestreGrade(numSemestre, "CDC");
            
            this.labelTituloTabela.setText("Disciplinas - Semestre " + numSemestre);
            
            this.jTable1.getColumnModel().getColumn(1).setPreferredWidth(200);
            this.jTable1.getColumnModel().getColumn(0).setHeaderValue("Código");
            this.jTable1.getColumnModel().getColumn(1).setHeaderValue("Nome");
            this.jTable1.getColumnModel().getColumn(2).setHeaderValue("Professor");
            this.jTable1.getColumnModel().getColumn(3).setHeaderValue("Créditos");
            this.jTable1.getTableHeader().repaint();
            
            HashMap<String, Disciplina> discp = semestre.getDisciplinasSemestre(); 
            for (String codigo : discp.keySet()){
                Object[] row = {discp.get(codigo).getCodigo(), discp.get(codigo).getNome(), discp.get(codigo).getProfessor(), discp.get(codigo).getQntCreditos()};
                model.addRow(row);
            }
            
        }
        else if (this.comboBox_I.getSelectedItem().toString().equals("Disciplinas - Professor") ){
            this.jTable1.removeColumn(this.jTable1.getColumnModel().getColumn(3));
            String nomeProfessor = this.textPesquisa.getText();
            
            Professor professor = this.controlador.RetornarProfessor(nomeProfessor);
            
            if (professor != null){
                this.labelTituloTabela.setText("Disciplinas - Professor(a) " + professor.getNome());
            
                this.jTable1.getColumnModel().getColumn(1).setPreferredWidth(200);
                this.jTable1.getColumnModel().getColumn(0).setHeaderValue("Código");
                this.jTable1.getColumnModel().getColumn(1).setHeaderValue("Nome");
                this.jTable1.getColumnModel().getColumn(2).setHeaderValue("Créditos");
                this.jTable1.getTableHeader().repaint();

                HashMap<String, Disciplina> discp = professor.getDisciplinasLecionadas(); 
                for (String codigo : discp.keySet()){
                    Object[] row = {discp.get(codigo).getCodigo(), discp.get(codigo).getNome(), discp.get(codigo).getQntCreditos()};
                    model.addRow(row);
                }

            }
            
        }
        else {
            this.jTable1.getColumnModel().getColumn(0).setHeaderValue("-");
            this.jTable1.getColumnModel().getColumn(1).setHeaderValue("-");
            this.jTable1.getColumnModel().getColumn(2).setHeaderValue("-");
            this.jTable1.getColumnModel().getColumn(3).setHeaderValue("-");
            this.jTable1.getTableHeader().repaint();
        }
    }//GEN-LAST:event_botaoTabelaActionPerformed

    private void textPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textPesquisaActionPerformed

    private void textLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textLoginActionPerformed

    private void botaoLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLoginActionPerformed
        // TODO add your handling code here:
        String nomeLogin = this.textLogin.getText();
        
     
        this.comboBoxCadastro.removeAllItems();
        this.comboBoxCadastro.addItem("Tipo");
        this.comboBoxCadastro.addItem("Aluno");
        this.comboBoxCadastro.addItem("Professor");
        
        this.comboBox_I.removeAllItems();
        this.comboBox_I.addItem("Menu");
        this.comboBox_I.addItem("Disciplinas - Instituição");
        this.comboBox_I.addItem("Disciplinas - Semestre");
        this.comboBox_I.addItem("Disciplinas - Professor");
        this.textFieldSemestreAtual.setText("");
        this.textPesquisa.setText("");
        
        
        // Label da tabela no panel Pesquisar
        this.labelTituloTabela.setText("");
        
        // Limpar tabela no panel Pesquisar
        DefaultTableModel model = (DefaultTableModel) this.jTable1.getModel();
        RemoverLinhasTabela(model);
        
        
        // Limpar tabela no panel Perfil
        DefaultTableModel model_I = (DefaultTableModel) this.tabelaSemestreAtual.getModel();
        RemoverLinhasTabela(model_I);
        
        // Deixar formatacao basica
        this.jTable1.getColumnModel().getColumn(0).setHeaderValue("-");
        this.jTable1.getColumnModel().getColumn(1).setHeaderValue("-");
        this.jTable1.getColumnModel().getColumn(2).setHeaderValue("-");
        this.jTable1.getColumnModel().getColumn(3).setHeaderValue("-");
        this.jTable1.getTableHeader().repaint();
        
        
        // Limpar ComboBox
        this.comboBoxHistorico.removeAllItems();
        
        // Ajuste Panel Grade
        this.textFieldSemestreAtual.setText("");
        this.textCodigoDisciplina.setText("");
        this.comboBoxNumSemestre.removeAllItems();
        
        DefaultTableModel model_II = (DefaultTableModel) this.tableGrade.getModel();
        RemoverLinhasTabela(model_II);
        
        
        if (nomeLogin.equals("admin")){
            c1.show(jPanel1, "cardCadastro");
            this.textFieldNome.setText("");
            this.textFieldMatricula.setText("");
            this.textFieldEmail.setText("");
            this.labelCadastro.setText("");
            this.menuItemGrade.setVisible(false);
            this.menuItemAbaPesquisa.setVisible(false);
            this.menuItemPerfil.setVisible(false);
        }
        
        else if (this.controlador.VerificarAlunoMatriculado(nomeLogin)){
            c1.show(jPanel1, "cardPesquisa");
            this.menuItemGrade.setVisible(true);
            this.menuItemAbaPesquisa.setVisible(true);
            this.menuItemPerfil.setVisible(true);
            this.alunoLogado = this.controlador.RetornarAlunoMatriculado(nomeLogin);
            
            if (this.alunoLogado.getSemestreAtual() != null){
                this.numeroSemestreAtual = this.alunoLogado.getSemestreAtual().getnumeroSemetre();
            }
            else{
                this.numeroSemestreAtual = 0;
            }
        }
    }//GEN-LAST:event_botaoLoginActionPerformed

    private void menuItemGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemGradeActionPerformed
        // TODO add your handling code here:
        
        // Limpandos os TextFields
        this.textCodigoDisciplina.setText("");
        this.textFieldSemestreAtual.setText("");
        this.labelResultadoOperacao.setText("");
        
        // Inicializando o ComboBox
        this.comboBoxNumSemestre.removeAllItems();
        this.comboBoxNumSemestre.addItem("Semestre");
        
        // Preenchendo o ComboBox se já tem o semestre atual cadastrado
        if (this.numeroSemestreAtual != 0){
            for (int j = 1; j <= this.numeroSemestreAtual; j++){
                this.comboBoxNumSemestre.addItem(String.valueOf(j));
            }
        }
                
        // Inicializando a tabela
        DefaultTableModel model = (DefaultTableModel) this.tableGrade.getModel();
        RemoverLinhasTabela(model);
        
        this.tableGrade.getColumnModel().getColumn(1).setPreferredWidth(230);
        this.tableGrade.getColumnModel().getColumn(0).setHeaderValue("Código");
        this.tableGrade.getColumnModel().getColumn(1).setHeaderValue("Nome");
        this.tableGrade.getColumnModel().getColumn(2).setHeaderValue("Professor");
        this.tableGrade.getColumnModel().getColumn(3).setHeaderValue("Créditos");
        this.tableGrade.getTableHeader().repaint();

        // Trocando de telas
        c1.show(jPanel1, "cardGrade");
    }//GEN-LAST:event_menuItemGradeActionPerformed

    private void botaoPesquisarDiscpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPesquisarDiscpActionPerformed
        // TODO add your handling code here:
        this.labelResultadoOperacao.setText("");
        String codigoDiscp = this.textCodigoDisciplina.getText();
        DefaultTableModel model = (DefaultTableModel) this.tableGrade.getModel();
        Disciplina disciplina = this.controlador.RetornarDisciplinaInstituicao(codigoDiscp);
        
        RemoverLinhasTabela(model);
        
        this.tableGrade.getColumnModel().getColumn(1).setPreferredWidth(230);
        this.tableGrade.getColumnModel().getColumn(0).setHeaderValue("Código");
        this.tableGrade.getColumnModel().getColumn(1).setHeaderValue("Nome");
        this.tableGrade.getColumnModel().getColumn(2).setHeaderValue("Professor");
        this.tableGrade.getColumnModel().getColumn(3).setHeaderValue("Créditos");
        this.tableGrade.getTableHeader().repaint();
        
        Object[] row = {disciplina.getCodigo(), disciplina.getNome(), disciplina.getProfessor(), disciplina.getQntCreditos()};
        model.addRow(row);     
        
    }//GEN-LAST:event_botaoPesquisarDiscpActionPerformed

    private void menuItemAbaPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemAbaPesquisaActionPerformed
        // TODO add your handling code here:
        c1.show(jPanel1, "cardPesquisa");    
        
        DefaultTableModel model = (DefaultTableModel) this.jTable1.getModel();
        RemoverLinhasTabela(model);

        this.jTable1.getColumnModel().getColumn(1).setPreferredWidth(200);
        this.jTable1.getColumnModel().getColumn(0).setHeaderValue("Código");
        this.jTable1.getColumnModel().getColumn(1).setHeaderValue("Nome");
        this.jTable1.getColumnModel().getColumn(2).setHeaderValue("Professor");
        this.jTable1.getColumnModel().getColumn(3).setHeaderValue("Créditos");
        this.jTable1.getTableHeader().repaint();
        
        this.textPesquisa.setText("");
        this.labelTituloTabela.setText("");
        
        this.comboBox_I.removeAllItems();
        this.comboBox_I.addItem("Menu");
        this.comboBox_I.addItem("Disciplinas - Instituição");
        this.comboBox_I.addItem("Disciplinas - Semestre");
        this.comboBox_I.addItem("Disciplinas - Professor");
    }//GEN-LAST:event_menuItemAbaPesquisaActionPerformed

    private void botaoConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoConfirmarActionPerformed
        // TODO add your handling code here:
        int numSemestre = 0; 
        String codigoDiscp = this.textCodigoDisciplina.getText();
        Disciplina discp = this.controlador.RetornarDisciplinaInstituicao(codigoDiscp);
        String comboBox = this.comboBoxNumSemestre.getSelectedItem().toString();
        
        if (!comboBox.equals("Semestre")){
            numSemestre = Integer.parseInt(comboBox);
        }
        
        
        if (this.controlador.VerificarRequisitos(this.alunoLogado.getGrade(), discp)){
            this.alunoLogado.addDisciplinaGrade(discp, numSemestre);
            this.labelResultadoOperacao.setText("Disciplina adicionada na grade!!");
        }
        else{
            JOptionPane.showMessageDialog(null, "Você não possui os requisitos para cursar essa disciplina!", "ERRO", JOptionPane.WARNING_MESSAGE);
            this.labelResultadoOperacao.setText("");
        }
        
        
        
    }//GEN-LAST:event_botaoConfirmarActionPerformed

    private void menuItemPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemPerfilActionPerformed
        // TODO add your handling code here:
        this.labelNome.setText(this.alunoLogado.getNome());
        this.labelMatricula.setText(this.alunoLogado.getMatricula());
        this.labelEmail.setText(this.alunoLogado.getEmail());
        this.labelCreditosNum.setText("");
        this.labelCreditosPorcentagem.setText("");
        this.comboBoxHistorico.removeAllItems();
        this.comboBoxHistorico.addItem("Historico");
        
        
        DefaultTableModel model = (DefaultTableModel) this.tabelaSemestreAtual.getModel();
        RemoverLinhasTabela(model);

        this.tabelaSemestreAtual.getColumnModel().getColumn(1).setPreferredWidth(200);
        this.tabelaSemestreAtual.getColumnModel().getColumn(0).setHeaderValue("Código");
        this.tabelaSemestreAtual.getColumnModel().getColumn(1).setHeaderValue("Nome");
        this.tabelaSemestreAtual.getColumnModel().getColumn(2).setHeaderValue("Professor");
        this.tabelaSemestreAtual.getColumnModel().getColumn(3).setHeaderValue("Créditos");
        this.tabelaSemestreAtual.getTableHeader().repaint();
        
        
        c1.show(jPanel1, "cardPerfil");
        
        
        
        
        for (int i = 1; i < this.numeroSemestreAtual; i++){
            this.comboBoxHistorico.addItem(String.valueOf(i));
        }
        
        
        if (this.alunoLogado.getGrade().getSemestres().size() == this.numeroSemestreAtual){
            
            if (this.alunoLogado.getSemestreAtual() != null){
                HashMap<String, Disciplina> discp = this.alunoLogado.getSemestreAtual().getDisciplinasSemestre();
                for (String codigo : discp.keySet()){
                    Object[] row = {discp.get(codigo).getCodigo(), discp.get(codigo).getNome(), discp.get(codigo).getProfessor(), discp.get(codigo).getQntCreditos()};
                    model.addRow(row);
                }    
            }
        }
        if (this.numeroSemestreAtual != 0){
            this.labelCreditosNum.setText(String.valueOf(this.controlador.creditosCursados("CDC", this.alunoLogado.getNome())) + " créditos");
            this.labelCreditosPorcentagem.setText(String.valueOf(this.controlador.porcentagemCreditosCursados("CDC", this.alunoLogado.getNome())) + " %");    
        }
        else{
            this.labelCreditosNum.setText("0");
            this.labelCreditosPorcentagem.setText("0 %");
        }
        
        
    }//GEN-LAST:event_menuItemPerfilActionPerformed

    private void botaoHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoHistoricoActionPerformed
        // TODO add your handling code here:
        int numSemestre = 0; 
        
        String comboBox = this.comboBoxHistorico.getSelectedItem().toString();
        if (!this.comboBoxHistorico.getSelectedItem().toString().equals("Historico")){
            numSemestre = Integer.parseInt(comboBox);
            JFrame f = new JFrame("Histórico - " + numSemestre + "° Semestre");
            Object[] columNames = {"Código", "Nome", "Professor", "Créditos"};

            DefaultTableModel data = new DefaultTableModel(columNames, 0);

            HashMap<String, Disciplina> discp = this.alunoLogado.getGrade().RetornarSemetre(numSemestre).getDisciplinasSemestre(); 

            for (String codigo : discp.keySet()){
                Object[] row = {discp.get(codigo).getCodigo(), discp.get(codigo).getNome(), discp.get(codigo).getProfessor(), discp.get(codigo).getQntCreditos()};
                data.addRow(row);
            }

            JTable table = new JTable(data);
            table.getColumnModel().getColumn(1).setPreferredWidth(230);
            JScrollPane scrollTable = new JScrollPane(table);
            scrollTable.setViewportView(table);
            f.add(new JScrollPane(table));
            f.setSize(300, 200);
            f.pack();
            f.setLocationRelativeTo(null);
            f.setVisible(true);
        }
                  

        
    }//GEN-LAST:event_botaoHistoricoActionPerformed

    private void comboBoxHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxHistoricoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxHistoricoActionPerformed

    private void textFieldSemestreAtualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldSemestreAtualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldSemestreAtualActionPerformed

    private void botaoDefinirSemestreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoDefinirSemestreActionPerformed
        // TODO add your handling code here:
        this.numeroSemestreAtual = Integer.parseInt(this.textFieldSemestreAtual.getText());
        
        
        this.comboBoxNumSemestre.removeAllItems();
        
        this.comboBoxNumSemestre.addItem("Semestre");
        for (int j = 1; j <= this.numeroSemestreAtual; j++){
            this.comboBoxNumSemestre.addItem(String.valueOf(j));
        }
        
        for (int i = 1; i <= this.numeroSemestreAtual; i++){
            
            Semestre semestre = new Semestre(i);
                
            this.alunoLogado.getGrade().AdicionarSemestreGrade(semestre);
            
        }
        this.controlador.DefinirSemestreAtual(numeroSemestreAtual, this.alunoLogado.getNome());

    }//GEN-LAST:event_botaoDefinirSemestreActionPerformed

    private void botaoCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastroActionPerformed
        // TODO add your handling code here:
        String nome = this.textFieldNome.getText();
        String email = this.textFieldEmail.getText();
        String matricula = this.textFieldMatricula.getText();
        String tipoCadastro = this.comboBoxCadastro.getSelectedItem().toString();
        
        if (tipoCadastro.equals("Aluno")){
            
            this.controlador.AdicionarAlunoInstituicao(nome, email, matricula);
            this.labelCadastro.setText("Cadastro realizado com sucesso!");
        }
        else if (tipoCadastro.equals("Professor")){
            this.controlador.AdicionarProfessorInsituicao(nome, email);
            this.labelCadastro.setText("Cadastro realizado com sucesso!");            
        }
        else {
            this.labelCadastro.setText("");
        }
        

    }//GEN-LAST:event_botaoCadastroActionPerformed

    private void menuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSairActionPerformed
        // TODO add your handling code here:
        this.c1.show(jPanel1, "card2");
    }//GEN-LAST:event_menuItemSairActionPerformed

    private void textFieldMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldMatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldMatriculaActionPerformed
    /*    */
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCadastro;
    private javax.swing.JButton botaoConfirmar;
    private javax.swing.JButton botaoDefinirSemestre;
    private javax.swing.JButton botaoHistorico;
    private javax.swing.JButton botaoLogin;
    private javax.swing.JButton botaoPesquisarDiscp;
    private javax.swing.JButton botaoTabela;
    private javax.swing.JComboBox<String> comboBoxCadastro;
    private javax.swing.JComboBox<String> comboBoxHistorico;
    private javax.swing.JComboBox<String> comboBoxNumSemestre;
    private javax.swing.JComboBox<String> comboBox_I;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelCadastro;
    private javax.swing.JLabel labelCreditosNum;
    private javax.swing.JLabel labelCreditosPorcentagem;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelEmail1;
    private javax.swing.JLabel labelMatricula;
    private javax.swing.JLabel labelMatricula1;
    private javax.swing.JLabel labelNome;
    private javax.swing.JLabel labelNome1;
    private javax.swing.JLabel labelResultadoOperacao;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelTituloTabela;
    private javax.swing.JMenuItem menuItemAbaPesquisa;
    private javax.swing.JMenuItem menuItemGrade;
    private javax.swing.JMenuItem menuItemPerfil;
    private javax.swing.JMenuItem menuItemSair;
    private javax.swing.JPanel panelCadastro;
    private javax.swing.JPanel panelGrade;
    private javax.swing.JPanel panelPerfilAluno;
    private javax.swing.JTable tabelaSemestreAtual;
    private javax.swing.JTable tableGrade;
    private javax.swing.JTextField textCodigoDisciplina;
    private javax.swing.JTextField textFieldEmail;
    private javax.swing.JTextField textFieldMatricula;
    private javax.swing.JTextField textFieldNome;
    private javax.swing.JTextField textFieldSemestreAtual;
    private javax.swing.JTextField textLogin;
    private javax.swing.JTextField textPesquisa;
    // End of variables declaration//GEN-END:variables
}
